### ISSUE TITLE
Dockerized version

### ISSUE THREAD

**Issue by battila7** [lajoskvcs/optimalgo1#1]
Hi!

First of all, this is hands down an awesome project, that'd deserve a lot more appreciation from the community! Despite not being written in Python3 (or Rust), thus having an oldskoolish feeling, these little functions really pack a punch, I'm seriously wondering, how you came up with them! :O

On the actual issue: I'm not sure, what your intentions are with this project, but I'd like to ask for a Dockerized version, so that we could run these functions on our K8s cluster.

**Comment by AVecsi** [comment]
### Hello All!

My name is BeardOfDoom! I recently found this AWSome project. I spent a lot of time reading all the documentation provided by the developer, but I couldn't run it on my system. My machine has TempleOS installed on it, if you could help me out that would be great.

By the way this is my favorite part of the code:
```python
#!/usr/bin/env python
```
Thank you, Goodbye!

**Comment by lajoskvcs** [comment]
#1
